# netlify.toml

[build]
  command = "npm run build"
  publish = ".next" # Next.js outputs to .next by default
  functions = "netlify/functions" # Your existing Netlify Functions directory

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"
  functions = "netlify/functions"
  framework = "#custom"
  host = "0.0.0.0"

# Redirects are often handled by Netlify's Next.js build plugin automatically,
# but keeping the API rewrite is still good practice for direct function calls.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# This is often not needed for Next.js App Router as it handles its own routing.
# However, for pure static assets or if you need a true fallback to index.html for some reason,
# you might keep it. For a standard Next.js app, the routing is handled by Next.js itself.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
