[build]
  # Add commands to clean npm cache and reinstall before building
  command = "npm cache clean --force && npm install && npm run build"
  publish = "out"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
