[build]
  command = "npm run build"
  publish = "out" # This should be 'out' when using output: 'export' in next.config.js
  functions = "netlify/functions" # Assuming your functions are here

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
