# netlify.toml

[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  publish = "build"
  functions = "netlify/functions"
  framework = "#custom"
  host = "0.0.0.0"

# =====================================================================
# CRITICAL: REDIRECTS ORDER.
# =====================================================================

# netlify.toml
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth-handler" # <--- CHANGE THIS LINE
  status = 200
  force = true

# Keep your other redirect rules as they are:
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200