[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions" # Assuming your functions are in a 'netlify/functions' directory

[dev]
  command = "npm start"
  targetPort = 3000
  publish = "public" # <-- CHANGE THIS LINE from "build" to "public"
  functions = "netlify/functions"
  framework = "#custom"
  host = "0.0.0.0"